# Generated by Django 3.0.3 on 2020-09-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetSale',
        ),
    ]
