# Generated by Django 3.0.3 on 2020-09-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_delete_detsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='date_joined',
            new_name='saledate',
        ),
    ]
