# Generated by Django 3.0.3 on 2020-09-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20200915_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='client',
            new_name='cli',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='saledate',
            new_name='date_joined',
        ),
    ]
