# Generated by Django 3.0.3 on 2020-09-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20200930_1154'),
        ('gestion', '0005_detsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detsale',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ProdServ'),
        ),
    ]
