# Generated by Django 3.0.3 on 2020-05-31 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='categoria',
        ),
    ]
