# Generated by Django 3.0.3 on 2020-05-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200531_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoria',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
