# Generated by Django 3.0.3 on 2020-06-25 18:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200613_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoria',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
