# Generated by Django 3.0.3 on 2020-10-27 16:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200719_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=tinymce.models.HTMLField(max_length=50, verbose_name='Descripción'),
        ),
    ]
