# Generated by Django 3.0.3 on 2020-10-27 17:09

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201027_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Imagen'),
        ),
    ]
