# Generated by Django 3.0.3 on 2020-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='thumbnail',
            field=models.FileField(upload_to='', verbose_name='Imagen'),
        ),
    ]
