# Generated by Django 3.0.3 on 2020-08-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200814_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='category',
        ),
    ]
