# Generated by Django 3.0.3 on 2020-08-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200815_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categoria',
        ),
    ]
