# Generated by Django 3.0.3 on 2020-08-16 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20200815_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoria',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='catego',
            new_name='categoria',
        ),
    ]
