# Generated by Django 3.0.3 on 2020-08-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20200815_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='thumbnail',
            field=models.FileField(upload_to='', verbose_name='Imagen'),
        ),
    ]
