# Generated by Django 3.0.3 on 2020-09-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_auto_20200818_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo',
            field=models.FloatField(default=0, verbose_name='Costo Unitario'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='costo',
            field=models.FloatField(default=0, verbose_name='Costo Unitario'),
        ),
    ]
