# Generated by Django 3.0.3 on 2020-09-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200930_1154'),
        ('inventario', '0012_auto_20200930_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
