# Generated by Django 3.0.3 on 2020-06-04 22:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=264)),
                ('apellido', models.CharField(max_length=264)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+521', max_length=128, region=None, unique=True)),
                ('mail', models.EmailField(blank=True, default='', max_length=264, unique=True)),
                ('rfc', models.CharField(blank=True, default='', max_length=264, unique=True)),
            ],
        ),
    ]
