# Generated by Django 3.0.3 on 2020-07-10 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200702_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(blank=True, default='', max_length=264),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, default='', max_length=264),
        ),
    ]
